Bump UT to v2.3.1
This fixes the build for people targetting latest GR4.

Error was:
    gnuradio4/bench/benchmark.hpp:871:25: error: no type named 'run_begin' in namespace 'boost::ut::events'
       auto on(ut::events::run_begin) -> void {} // no-op (required for Boost.UT >= v2.3.1)

Signed-off-by: Sergio Martins <sergio.martins@kdab.com>